### ISSUE TITLE
location of the notes file

### ISSUE THREAD

**Issue by brandelune** [rnkn/notes#2]
The main notes file seem to be sometimes at the same level as the file it relates to and sometimes at the level of the enclosing folder.

But the sub notes file seems to always be at the same level as the file it relates to.

Is there a way to make sure the main file is *always* at the same level as the file it relates to ?

**Comment by rnkn** [comment]
> The main notes file seem to be sometimes at the same level as the 
> file it relates to and sometimes at the level of the enclosing 
> folder.

I'm not sure if I totally get what you mean by "level" here? The notes 
files will always be in folders, they aren't really associated with a 
file per se.

Locating the notes files uses the Emacs function 
locate-dominating-file, which is documented:

> Starting at FILE, look up directory hierarchy for directory 
> containing NAME.

So say you're visiting a file, side-notes will look for a notes file 
first in the same directory as the file, then the enclosing directory, 
then in the enclosing directory of that, etc.

So if you have the following...

    /folder/folder/file.txt
    /folder/notes.txt

...and you want to use notes file...

    /folder/folder/notes.txt

...then you'd need to manually create it with C-x C-f.

Does that make sense?

**Comment by brandelune** [comment]
Ok. I understand better. So a note file is only "associated" to a folder and all the files in that folder will share the note file. 

So I guess what happened is that there was a note file in the enclosing folder created for a file that was there, but not in the same directory as my working file, so side-notes used the note file in the enclosing folder and I had to manually create one in the working folder to have side-notes use that one.

**Comment by rnkn** [comment]
Yes that's it. In truth there's no association, the file is just in the folder like any other.

I can see how it would be useful to have a convenience function to create a notes file in the current directory in the event you already have a notes file in a higher directory. I'll add this when I get a chance.

**Comment by brandelune** [comment]
Thank you for the confirmation. I think the easiest way to "fix" this, is to just document the behavior more precisely in your readme file.

**Comment by rnkn** [comment]
Updated the README (and added some behaviour to force visiting notes files in the current directory).

Could you please have a look and let me know if this is clearer?

**Comment by brandelune** [comment]
Excellent ! Thank you so much !
